services:
  api:
    volumes:
    - /www/wwwroot/restaurantcloudhub_uploads:/app/wwwroot
    build:
      context: .
      dockerfile: RestaurantSystem.WebAPI/Dockerfile
    container_name: restaurantcloudhub-api
    restart: unless-stopped
    network_mode: "host"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=127.0.0.1;Port=5432;Database=restauranthubdb;Username=RestaurantHubDb;Password=5X55X7XHkLBFbXmc
      JwtSettings__SecretKey: "JwtSettings\u003eHv}y|P,pjoA9ko1VO;vgdhtYzH}wq,He#Ld/2\u0026E\u0026]gW\u003c6hCW*eXB6s8SO\u0026W@5.-%,X8PN5i(pAPU4]7)@x1ol"
      JwtSettings__Issuer: RestaurantSystem
      JwtSettings__Audience: RestaurantSystemAPI
      Cors__AllowedOrigins__0: https://restaurantcloudhub.sawanhoney.com
      ForwardedHeaders__KnownIPNetworks__0: 127.0.0.1
      EmailSettings__SmtpHost: smtp.gmail.com
      EmailSettings__SmtpPort: 587
      EmailSettings__SmtpUser: khaled963sawan@gmail.com
      EmailSettings__SmtpPass: wpsd rszb oadt blis
      EmailSettings__FromName: Restaurant System
      EmailSettings__FromEmail: khaled963sawan@gmail.com

